<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXP6rIxu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXP6rIxu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXP6rIxu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXP6rIxu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXP6rIxu\App_KernelDevDebugContainer([
    'container.build_hash' => 'XP6rIxu',
    'container.build_id' => 'a226c6ae',
    'container.build_time' => 1662984509,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXP6rIxu');
